spring:
  application:
    name: boot
  datasource:
    master:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      url: jdbc:mysql://localhost:3307/test?readOnly=true
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
    slave2:
      url: jdbc:mysql://XXX/XXX?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&useSSL=false
      username: XXX
      password: XXX
      driver-class-name: com.mysql.jdbc.Driver
log:
  type: aspect